spring:
  application:
    name: product-services
  datasource:
    url: jdbc:h2:mem:product
    driver-class-name: org.h2.Driver
    username: product
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
server:
  port: 8080
  servlet.context-path: /product
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.lisseth.product
